service: shougi-room

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: ap-northeast-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "dynamodb:Scan"
        - "dynamodb:PutItem"
        - "dynamodb:GetItem"
        - "dynamodb:DeleteItem"
      Resource:
        - "arn:aws:dynamodb:ap-northeast-1:*:table/shougi*"
  websocketsApiName: ShougiRoomWebSocket
  websocketsApiRouteSelectionExpression: $request.body.action
functions:
  connect:
    handler: functions/connect.handler
    events:
      - websocket:
          route: $connect
  disconnect:
    handler: functions/disconnect.handler
    events:
      - websocket:
          route: $disconnect
  sendmessage:
    handler: functions/sendmessage.handler
    events:
      - websocket:
          route: sendmessage # will trigger if $request.body.action === "message"
resources:
  Resources:
    ConnectionTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: shougiConnections
        AttributeDefinitions:
          - AttributeName: connectionId
            AttributeType: S
        KeySchema:
          - AttributeName: connectionId
            KeyType: HASH
        SSESpecification:
          SSEEnabled: True
        BillingMode: PAY_PER_REQUEST #オンデマンド課金
